GestMusic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musiques/', include('musiques.urls'))
]

musiques/urls.py
from django.urls import path
#from .views import morceau_detail
from .views import MorceauDetailView, MorceauList
app_name = 'musiques'

urlpatterns = [
    #path('<int:pk>', morceau_detail, name='morceau_detail')
    path('<int:pk>', MorceauDetailView.as_view(), name='morceau_detail'),
    path('', MorceauList.as_view(), name='morceau_list'),
]

musiques/models.py
from django.db import models

# Create your models here.


class Morceau(models.Model):
    titre = models.CharField(max_length=64)
    artiste = models.CharField(max_length=64)
    date_sortie = models.DateField(null=True)

    def __str__(self):
        return '{self.titre} ({self.artiste})'.format(self=self)


class Artiste(models.Model):
    nom = models.CharField(max_length=64)

musiques/views.py
from django.shortcuts import render

from .models import Morceau
from django.views.generic import DetailView
from django.views.generic import ListView

# Create your views here.
from django.http import HttpResponse


def morceau_detail(request, pk):
    return HttpResponse('OK')


class MorceauDetailView(DetailView):
    model = Morceau


class MorceauList(ListView):
    model = Morceau

musiques/templates/musiques/morceau_detail.html
<ul>
    <li>{{object.titre}}</li>
    <li>{{object.artiste}}</li>
</ul>
<a href="{% url 'musiques:morceau_list' %}">
    Revenir a la liste
</a>

musiques/templates/musiques/morceau_list.html
<h2>Morceaux</h2>
<ul>
    {% for morceau in morceau_list %}
    <li>
        <h3>Morceau n°{{morceau.pk}}</h3>
        {{ morceau.titre }} par {{ morceau.artiste }}
    </li>
    {% endfor %}
</ul>